/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Animacion(props) {

  /* this.NewAnimation = this.NewAnimation.bind(this)
  const[animat,setAnimation] = useState(null) */
  /* useEffect(()=>{
    const Animation1 =()=>{
      useEffect(()=>{
        actions.GarraIzquierza.play();
        setAnimation(setAnimation)
      })
    }
    Animations1()
  },[]) */

  /* handleClick(()=>{
    this.props.onAnimate(this.state)
  }) */

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../models/Animacion.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0]}>
        <group position={[0, 100, 0]} />
      </group>
      <mesh
        material={materials.anisotropic56}
        geometry={nodes.acople_servo.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn31}
        geometry={nodes.Servo.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01002.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group name="ruedavs2001_ruedavs2004" position={[-1.05, 0.67, 1.37]} rotation={[Math.PI / 2, -0.16, 0]}>
        <mesh material={materials.anisotropic12} geometry={nodes.Malla003.geometry} />
        <mesh material={materials.anisotropic11} geometry={nodes.Malla003_1.geometry} />
      </group>
      <mesh
        material={materials.blinn27}
        geometry={nodes.Servo001.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn32}
        geometry={nodes.Servo002.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic19}
        geometry={nodes.MotorGear01001_MotorGear01001.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic35}
        geometry={nodes.MotorGear01001_MotorGear01003.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic29}
        geometry={nodes.MotorGear01001_MotorGear01004.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic34}
        geometry={nodes.MotorGear01001_MotorGear01005.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn11}
        geometry={nodes.MotorGear01001_MotorGear01006.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert12}
        geometry={nodes.MotorGear01001_MotorGear01007.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert13}
        geometry={nodes.MotorGear01001_MotorGear01008.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert14}
        geometry={nodes.MotorGear01001_MotorGear01010.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn17}
        geometry={nodes.MotorGear01001_MotorGear01011.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn22}
        geometry={nodes.MotorGear01001_MotorGear01012.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn26}
        geometry={nodes.MotorGear01001_MotorGear01013.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn23}
        geometry={nodes.MotorGear01001_MotorGear01014.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.051']}
        geometry={nodes.MotorGear01001_MotorGear01015.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01016.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn20}
        geometry={nodes.MotorGear01001_MotorGear01017.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn15}
        geometry={nodes.MotorGear01001_MotorGear01018.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.LedRojoON}
        geometry={nodes.MotorGear01001_MotorGear01019.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic60}
        geometry={nodes.MotorGear01001_MotorGear01020.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic16}
        geometry={nodes.MotorGear01001_MotorGear01021.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic15}
        geometry={nodes.MotorGear01001_MotorGear01022.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic14}
        geometry={nodes.MotorGear01001_MotorGear01023.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic18}
        geometry={nodes.MotorGear01001_MotorGear01024.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic8}
        geometry={nodes.MotorGear01001_MotorGear01025.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic51}
        geometry={nodes.MotorGear01001_MotorGear01026.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn30}
        geometry={nodes.MotorGear01001_MotorGear01027.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic21}
        geometry={nodes.MotorGear01001_MotorGear01028.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic21}
        geometry={nodes.MotorGear01001_MotorGear01029.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn9}
        geometry={nodes.MotorGear01001_MotorGear01030.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01031.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic59}
        geometry={nodes.MotorGear01001_MotorGear01032.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic24}
        geometry={nodes.MotorGear01001_MotorGear01033.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic38}
        geometry={nodes.MotorGear01001_MotorGear01034.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic38}
        geometry={nodes.MotorGear01001_MotorGear01035.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn8}
        geometry={nodes.MotorGear01001_MotorGear01036.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic38}
        geometry={nodes.MotorGear01001_MotorGear01037.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic40}
        geometry={nodes.MotorGear01001_MotorGear01038.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic39}
        geometry={nodes.MotorGear01001_MotorGear01039.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.033']}
        geometry={nodes.MotorGear01001_MotorGear01040.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic20}
        geometry={nodes.MotorGear01001_MotorGear01041.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic57}
        geometry={nodes.MotorGear01001_MotorGear01042.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn6}
        geometry={nodes.MotorGear01001_MotorGear01043.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn5}
        geometry={nodes.MotorGear01001_MotorGear01044.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn2}
        geometry={nodes.MotorGear01001_MotorGear01045.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn21}
        geometry={nodes.MotorGear01001_MotorGear01046.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn7}
        geometry={nodes.MotorGear01001_MotorGear01047.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic51}
        geometry={nodes.MotorGear01001_MotorGear01048.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.LedAmarilloON}
        geometry={nodes.MotorGear01001_MotorGear01049.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.LedVerderON}
        geometry={nodes.MotorGear01001_MotorGear01050.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn20}
        geometry={nodes.MotorGear01001_MotorGear01051.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn15}
        geometry={nodes.MotorGear01001_MotorGear01052.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn20}
        geometry={nodes.MotorGear01001_MotorGear01053.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn15}
        geometry={nodes.MotorGear01001_MotorGear01054.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.061']}
        geometry={nodes.MotorGear01001_MotorGear01055.geometry}
        position={[-0.87, -0.77, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert14}
        geometry={nodes.MotorGear01001_MotorGear01056.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn17}
        geometry={nodes.MotorGear01001_MotorGear01057.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn10}
        geometry={nodes.MotorGear01001_MotorGear01059.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.065']}
        geometry={nodes.MotorGear01001_MotorGear01060.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn10}
        geometry={nodes.MotorGear01001_MotorGear01062.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.062']}
        geometry={nodes.MotorGear01001_MotorGear01063.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01065.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.071']}
        geometry={nodes.MotorGear01001_MotorGear01066.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01068.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.068']}
        geometry={nodes.MotorGear01001_MotorGear01069.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01071.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.077']}
        geometry={nodes.MotorGear01001_MotorGear01072.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01074.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.074']}
        geometry={nodes.MotorGear01001_MotorGear01075.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01077.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.083']}
        geometry={nodes.MotorGear01001_MotorGear01078.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01080.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01081.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn18}
        geometry={nodes.MotorGear01001_MotorGear01083.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn17}
        geometry={nodes.MotorGear01001_MotorGear01084.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn18}
        geometry={nodes.MotorGear01001_MotorGear01086.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn17}
        geometry={nodes.MotorGear01001_MotorGear01087.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn18}
        geometry={nodes.MotorGear01001_MotorGear01089.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn17}
        geometry={nodes.MotorGear01001_MotorGear01090.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn11}
        geometry={nodes.MotorGear01001_MotorGear01091.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert11}
        geometry={nodes.MotorGear01001_MotorGear01092.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn13}
        geometry={nodes.MotorGear01001_MotorGear01093.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert9}
        geometry={nodes.MotorGear01001_MotorGear01094.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert10}
        geometry={nodes.MotorGear01001_MotorGear01095.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.96, 0.96, 0.96]}
      />
      <mesh
        material={materials.blinn11}
        geometry={nodes.MotorGear01001_MotorGear01096.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert8}
        geometry={nodes.MotorGear01001_MotorGear01097.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn11}
        geometry={nodes.MotorGear01001_MotorGear01098.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert5}
        geometry={nodes.MotorGear01001_MotorGear01099.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn11}
        geometry={nodes.MotorGear01001_MotorGear01100.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert6}
        geometry={nodes.MotorGear01001_MotorGear01101.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert7}
        geometry={nodes.MotorGear01001_MotorGear01102.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01103.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert15}
        geometry={nodes.MotorGear01001_MotorGear01104.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert16}
        geometry={nodes.MotorGear01001_MotorGear01105.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01106.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert15}
        geometry={nodes.MotorGear01001_MotorGear01107.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01108.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert17}
        geometry={nodes.MotorGear01001_MotorGear01109.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01110.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert17}
        geometry={nodes.MotorGear01001_MotorGear01111.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert18}
        geometry={nodes.MotorGear01001_MotorGear01112.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01113.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert19}
        geometry={nodes.MotorGear01001_MotorGear01114.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert20}
        geometry={nodes.MotorGear01001_MotorGear01115.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn19}
        geometry={nodes.MotorGear01001_MotorGear01116.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert19}
        geometry={nodes.MotorGear01001_MotorGear01117.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic19}
        geometry={nodes.MotorGear01001_MotorGear01118.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic35}
        geometry={nodes.MotorGear01001_MotorGear01119.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic29}
        geometry={nodes.MotorGear01001_MotorGear01120.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic34}
        geometry={nodes.MotorGear01001_MotorGear01121.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01122.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01123.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic43}
        geometry={nodes.MotorGear01001_MotorGear01124.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01125.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01126.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic44}
        geometry={nodes.MotorGear01001_MotorGear01127.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01128.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01129.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic45}
        geometry={nodes.MotorGear01001_MotorGear01130.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01131.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01132.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic46}
        geometry={nodes.MotorGear01001_MotorGear01133.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01134.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01135.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic47}
        geometry={nodes.MotorGear01001_MotorGear01136.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01137.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01138.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic42}
        geometry={nodes.MotorGear01001_MotorGear01139.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01140.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn10}
        geometry={nodes.MotorGear01001_MotorGear01141.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic48}
        geometry={nodes.MotorGear01001_MotorGear01142.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01143.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01144.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01145.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01146.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01147.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01148.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01149.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01150.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01151.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['phong2SG.013']}
        geometry={nodes.MotorGear01001_MotorGear01152.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['phong2SG.012']}
        geometry={nodes.MotorGear01001_MotorGear01153.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01154.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic58}
        geometry={nodes.MotorGear01001_MotorGear01155.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01156.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic27}
        geometry={nodes.MotorGear01001_MotorGear01157.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic36}
        geometry={nodes.MotorGear01001_MotorGear01158.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic28}
        geometry={nodes.MotorGear01001_MotorGear01159.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.167']}
        geometry={nodes.MotorGear01001_MotorGear01160.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic50}
        geometry={nodes.MotorGear01001_MotorGear01161.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.164']}
        geometry={nodes.MotorGear01001_MotorGear01162.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic49}
        geometry={nodes.MotorGear01001_MotorGear01163.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic26}
        geometry={nodes.MotorGear01001_MotorGear01164.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic26}
        geometry={nodes.MotorGear01001_MotorGear01165.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic24}
        geometry={nodes.MotorGear01001_MotorGear01166.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic24}
        geometry={nodes.MotorGear01001_MotorGear01167.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic26}
        geometry={nodes.MotorGear01001_MotorGear01168.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic25}
        geometry={nodes.MotorGear01001_MotorGear01169.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic24}
        geometry={nodes.MotorGear01001_MotorGear01170.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic26}
        geometry={nodes.MotorGear01001_MotorGear01171.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic22}
        geometry={nodes.MotorGear01001_MotorGear01172.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.lambert2}
        geometry={nodes.MotorGear01001_MotorGear01173.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Material.177']}
        geometry={nodes.MotorGear01001_MotorGear01174.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic23}
        geometry={nodes.MotorGear01001_MotorGear01175.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic61}
        geometry={nodes.MotorGear01001_MotorGear01176.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic62}
        geometry={nodes.MotorGear01001_MotorGear01177.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.blinn10}
        geometry={nodes.MotorGear01001_MotorGear01178.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.anisotropic41}
        geometry={nodes.MotorGear01001_MotorGear01179.geometry}
        position={[-0.99, -0.01, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group name="ruedavs2000_ruedavs2002" position={[-1, 0.66, -1.31]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials.anisotropic6} geometry={nodes.Malla186.geometry} />
        <mesh material={materials.anisotropic7} geometry={nodes.Malla186_1.geometry} />
      </group>
      <mesh
        name="Garra_Vs2_"
        material={materials.blinn29}
        geometry={nodes.Garra_Vs2_.geometry}
        position={[-1.85, 0.8, 0.55]}
        rotation={[0, Math.PI / 3, 0]}
        scale={[-0.02, -0.02, -0.02]}
      />
      <mesh
        name="Garra_Vs2_001"
        material={materials.blinn29}
        geometry={nodes.Garra_Vs2_001.geometry}
        position={[-1.85, 0.8, -0.45]}
        rotation={[0, -Math.PI / 3, Math.PI]}
        scale={[0.03, 0.02, 0.03]}
      />
    </group>
  )
}

useGLTF.preload('../../../models/Animacion.glb')
